### PR TITLE
drizzle_row_buffer(): clear "result->field_sizes" before buffering fields

### PR DESCRIPTION
**Pull request by chenzhuoyu**
In src/row.cc:121

```cpp
  if (result->row == NULL)
  {
    drizzle_set_error(result->con, __func__, "Failed to allocate.");
    *ret_ptr= DRIZZLE_RETURN_MEMORY;
    return NULL;
  }

  result->field_sizes= new (std::nothrow) size_t[result->column_count]; // HERE
  if (result->field_sizes == NULL)
  {
    drizzle_set_error(result->con, __func__, "Failed to allocate.");
    *ret_ptr= DRIZZLE_RETURN_MEMORY;
    return NULL;
  }
```

After allocated the "field_sizes" buffer, it's uninitialized ("size_t" is essentially "unsigned long" and has no constructors, thus not initialize by compiler), and "drizzle_field_buffer" may give less columns than "result->column_count" since NULL fields are not buffered.

So the last few elements of "result->field_sizes" may be some ramdom garbage.

Later this value is being used to create column buffers in result.cc:381
```cpp
    for (x= 0; x < result->column_count; x++)
    {
      if (result->field_sizes[x] > 0)
      {
        result->row_list[result->row_current - 1][x]= new char[result->field_sizes[x]+1](); // HERE
        memcpy(result->row_list[result->row_current - 1][x], row[x], result->field_sizes[x]);
      }
    }
```

Which may cause serious problems.

This patch added "memset()" after allocating memory and checking for null pointer to initialize the "field_sizes" array.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Could you rebase to clean up the merge commits ?

**Comment by andreas-bok-sociomantic** [comment]
> Could you rebase to clean up the merge commits ? 

Against `v5.5.x`. We will release the patch as part of `v5.5.2`, `v5.6.1` and `v6.0.1`. 

Thus only a079dd8 should be in the PR. 

Great work and thanks a lot for the contribution @chenzhuoyu :)

**Comment by andreas-bok-sociomantic** [comment]
Also could you add this to the commit message? 

> Fixes the bug: 
After allocated the "field_sizes" buffer, 
it's uninitialized ("size_t" is essentially 
"unsigned long" and has no constructors, 
thus not initialize by compiler), and 
"drizzle_field_buffer" may give less columns 
than "result->column_count" since NULL fields 
are not buffered.
>
> So the last few elements of "result->field_sizes" 
may be some ramdom garbage.

**Comment by chenzhuoyu** [comment]
...... I'm trying to get rid of the "Merge branch ..." message but with no luck ... :(

**Comment by andreas-bok-sociomantic** [comment]
> ...... I'm trying to get rid of the "Merge branch ..." message but with no luck ... :(

Try to make a new branch and do a `git hard --reset v5.5.x` for that one and then cherrypick the last commit from your patch fix branch

**Comment by chenzhuoyu** [comment]
...... Oops...[Facepalm]

**Comment by mathias-lang-sociomantic** [comment]
You can do the following (assuming a clean state):
- `git checkout  1d51ea9` (that's v5.5.x's HEAD)
- `git checkout -b add-missing-initialization` (or whatever branch name you want)
- `git cherry-pick a079dd8cdee9dc277fbc2f14b8f82da691e3f2e6`
- Then push it, and open a new P.R. (Your P.R. is currently using your own `v6.x.x`, which I'm sure is not what you want to do ;) ).

Feel free to shout if it doesn't work.

P.S: You might be interested in reading [this](https://git-scm.com/book/zh) ;)

**Comment by chenzhuoyu** [comment]
OK, I'll try this tomorrow, it's 11:13pm in my country [Facepalm] Thanks for the instructions ;)

**Comment by andreas-bok-sociomantic** [comment]
> OK, I'll try this tomorrow, it's 11:13pm in my country [Facepalm] Thanks for the instructions ;)

No rush. Good night :)

**Comment by chenzhuoyu** [comment]
I created a new pull request (#145), it seems working

**Comment by andreas-bok-sociomantic** [comment]
Closed in favour of #145

**Pull request closed without merging**
