### PR TITLE
Build deb package on travis-ci

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
Add `make deb` to travis build steps

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
LGTM but is this still needed @leandro-lucarella-sociomantic ?

**Comment by leandro-lucarella-sociomantic** [comment]
I think is only useful to check that there are no errors while building the package. Not sure it adds much value, but I guess it doesn't hurt either.

**Comment by andreas-bok-sociomantic** [comment]
Ok, so it is the `install` target which should build the library and deb? 
And is that the last piece missing in the puzzle to add the project to an apt repo?

**Comment by ben-palmer-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 595bd9fa8ec4af373c5d13836e625309f1b0bcc6, new (rebased) HEAD is 11e51fb5d7f98e15f6808c181c371e69e6c771d5

**Pull request closed without merging**
