### PR TITLE
Add clang compiler to travis config

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
The PR enables CI testing for clang

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
blocked on #57, needs to be rebase on that PR

**Comment by andreas-bok-sociomantic** [comment]
Unblocked

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Comment by ben-palmer-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 0184027495f62de8368bf554fe8e18b2fcb318f9, new (rebased) HEAD is dfe3e3ad0373a4e3ad3e27862ee1142d8d9b36b1

**Pull request closed without merging**
