### PR TITLE
Remove temp file generated by sphinx m4 macro

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
Fixes error when running `make distcheck``

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
Is the commit title a bit double negative. Could it be `Remove version_file from sphinx m4 macro`?

**Comment by andreas-bok-sociomantic** [comment]
> Is the commit title a bit double negative. Could it be Remove version_file from sphinx m4 macro?

Will change it to: "Remove version test temp file with sphinx m4 macro"

**Comment by andreas-bok-sociomantic** [comment]
Fixed commit msg and PR title

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Pull request merged**
