### PR TITLE
Change project directory structure

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
Changes the directory layout of the project to: 

```
- src
  [source files]
- include
  - libdrizzle-redux
    [header files] 
```

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
Blocked until next minor release

**Comment by andreas-bok-sociomantic** [comment]
Updated on latest v6.x.x

**Comment by andreas-bok-sociomantic** [comment]
#97 and #103 should be merged before this PR

**Comment by andreas-bok-sociomantic** [comment]
@leandro-lucarella-sociomantic wondering if you could take a look at the sanity of this PR. :)

**Comment by leandro-lucarella-sociomantic** [comment]
Tomorrow hopefully :)

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Seems reasonable to me. I see this as just one commit (moving files around and adjusting everything to work with the new layout). Given that it might be a complex project structure and you had to take care of many small details, I don't mind if you prefer to keep it as small commits, but in general a change like this I would do it in one commit.

**Comment by andreas-bok-sociomantic** [comment]
> , but in general a change like this I would do it in one commit.

I see, the separation into commits was more for my own sake, and to make it easier to see the changes. 
But I am fine with squashing it into one commit once any comments have been addressed.

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, I can see how getting some order in the type and amounts of changes you needed to make must have been useful and again, if you think it adds clarity to leave it separated, for me is OK too (as long as this is merged and not rebased, so in terms of source control is seen as some sort of atomic unit).

**Comment by ben-palmer-sociomantic** [comment]
One thing I wondered about this is why we have `+5,533 −265` line changes? It seems to me we should have about an even number of lines changed.

**Comment by andreas-bok-sociomantic** [comment]
> One thing I wondered about this is why we have +5,533 −265 line changes? It seems to me we should have about an even number of lines changed.

Right. I suspect it relates to the approach in the PR. Luca pointed that the normal procedure was to have all changes in _one_ commit. 
I will push again once I have resolved the conflicts in the PR.

**Comment by andreas-bok-sociomantic** [comment]
Reordered and squashed the commits to make the diff more sane. 
Rebased on latest v6.x.x

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Pull request merged**
