### PR TITLE
Update submodule beaver from v0.1.1 to v0.1.4

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
The `make deb` step fails with the trace

> Created package {:path=>"libdrizzle-redux_5.6.4+20\~g5514a7a-trusty_amd64.deb"}
Created package {:path=>"libdrizzle-redux-dbg_5.6.4+20\~g5514a7a-trusty_amd64.deb"}
Invalid package configuration: Cannot package the path './install/usr/lib/libdrizzle-redux.so', does it exist? {:level=>:error}
make: *** [deb] Error 1

I tested `make deb` locally with the same error. However checking the output written by `make install` into the `$ROOT/deb/install` dir confirms that the path **does** exist. 

I will block it until the problem has been solved

**Comment by andreas-bok-sociomantic** [comment]
Seems to me a problem with the new release of fpm, [v1.9.2](https://github.com/jordansissel/fpm/releases/tag/v1.9.2). 
Building with latest version on v1.8.x, [v1.8.1](https://github.com/jordansissel/fpm/releases/tag/v1.8.1) doesn't fail.

**Comment by andreas-bok-sociomantic** [comment]
#199 ~~provides a fix by using fpm version 1.8.1 on travis to build the deb.~~
Fixes the configuration by specifying the full install path as cmd arg to **FPM**, i.e. 
```
fpm -s dir ... \
$so_libname=/usr/lib/$so_filename
```

**Comment by andreas-bok-sociomantic** [comment]
@leandro-lucarella-sociomantic, are deb builds failing for other tsunami projects as well with fpm v1.9.2 ?

**Comment by andreas-bok-sociomantic** [comment]
Opened issue in FPM, https://github.com/jordansissel/fpm/issues/1395

**Comment by leandro-lucarella-sociomantic** [comment]
I wonder how upgrading beaver triggered all this... Ah, probably because you are not using cachalot and just installing the latest fpm on your own?

**Comment by andreas-bok-sociomantic** [comment]
> I wonder how upgrading beaver triggered all this... Ah, probably because you are not using cachalot and just installing the latest fpm on your own?

Yes, just running `gem install fpm` in `.travis.yml` and coincidentally the v1.9.x releases were all released after the last PR/release in libdrizzle-redux. 
So true, just indirectly caused by the upgrade of beaver.

**Comment by leandro-lucarella-sociomantic** [comment]
> @leandro-lucarella-sociomantic, are deb builds failing for other tsunami projects as well with fpm v1.9.2 ?

Not that I know of, but other tsunami projects are using cachalot which is pinning the version of all major programs, like fpm, to avoid this kind of issues (be able to upgrade versions when you are ready to do so instead of having upgrades thrown into your face when you least expect it :D).

**Comment by andreas-bok-sociomantic** [comment]
>  (be able to upgrade versions when you are ready to do so instead of having upgrades thrown into your face when you least expect it :D).

`libdrizzle-redux` is bleeding edge even in the blessed repo. 
But admittedly might be better to pin the FPM version to v1.8.1 until the bug is fixed in FPM or I get around to use `camelot` sorry `cachelot` :)

**Comment by ben-palmer-sociomantic** [comment]
LGTM, is it still blocked for a reason?

**Comment by andreas-bok-sociomantic** [comment]
Ah, no forgot to unblock after rebasing on v5.5.x. it's good to go

**Pull request merged**
