### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
add doc related files to .gitignore and sort file

fix incorrect formatting

update library name in compiling.rst

fix paths for html logo and favicon

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
LGTM but it might be better to separate all the unrelated changes in to separate commits.

**Comment by andreas-bok-sociomantic** [comment]
Split PR into separate commits

**Comment by ben-palmer-sociomantic** [comment]
LGTM, two small things:
The commit title `Fix errors sphinx doc configuration` should be `Fix errors in sphinx doc configuration`
and for the commit `Modify target for cleaning generated docs` is a more accurate title `Add target for cleaning generated docs`?

**Comment by andreas-bok-sociomantic** [comment]
Rephrased ci msgs based on comments from @ben-palmer-sociomantic

**Comment by ben-palmer-sociomantic** [comment]
Sorry, another small thing but the commit message for `Add target for cleaning generated docs` might be better as `Added makefile clean target that removes generated files from building documentation` (so a missing "that").

**Comment by andreas-bok-sociomantic** [comment]
Rephrased the ci msg to make it even more succinct :)

**Comment by ben-palmer-sociomantic** [comment]
Ah, found another type in the commit message for `Update documentation with new lib name`, there are two "when"s.

**Comment by andreas-bok-sociomantic** [comment]
Fixed duplicate `when`,

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Comment by ben-palmer-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 7c17ea994faedb6cf208726fab3fbff7ee1824f6, new (rebased) HEAD is efe4cabf8c23a72b8cc72cefe5ef97bd9ca135a5

**Pull request closed without merging**
