### PR TITLE
Build RPM package with fpm

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
- modify rpm build script to use fpm
- delete obsolete files
- add newly rpm package files to .gitignore

addresses #29

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
Is it possible to have one copy of the build file for both the rpm and deb builds?

**Comment by andreas-bok-sociomantic** [comment]
> Is it possible to have one copy of the build file for both the rpm and deb builds?

I will check with @leandro-lucarella-sociomantic on what would be the normal approach for building distributions.

Currently the build files are almost identical, in which case the some dist specific argument for fpm could be passed to `build` 

Also the original `rpm` build target was creating packages for multiple architectures, [`rpm/include.am`](https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/master/rpm/include.am)

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not sure really what would be the best approach for this. I consider including packaging on the "upstream" repo only a best-effort, as every distribution has their own conventions.

**Comment by andreas-bok-sociomantic** [comment]
Blocked until more best practice for rpm packaging has been further investigated.

**Pull request closed without merging**
