### PR TITLE
Remove obsolete dependencies from deb packages

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
Fix wrong fpm config in build script

update fpm --category arg, to give correct
section information for deb package

removed dependencies:
- autoconf
- zlib1g-dev (replace by zlib1g runtime lib)
- libtool

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
Related issue in infrastructure: https://github.com/sociomantic/infrastructure/issues/2126

**Comment by andreas-bok-sociomantic** [comment]
any comments @leandro-lucarella-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
Nope, LGTM. They all seem to be build dependencies anyway!

**Comment by leandro-lucarella-sociomantic** [comment]
But maybe you need to include the library dependency (`zlib1g` and I don't know if anything else, maybe do a `ldd` to the `so` to find out).

**Comment by andreas-bok-sociomantic** [comment]
> zlib1g and I don't know if anything else, maybe do a ldd to the so to find out

Yes zlib is  needed: 

```
ldd libdrizzle-redux.so.9.0.0
    linux-vdso.so.1 =>  (0x00007ffe45b69000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fedb1db9000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fedb1ab5000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fedb16f0000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fedb13ea000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fedb21ed000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fedb11d4000)
```

**Comment by andreas-bok-sociomantic** [comment]
test this please jenkins

**Comment by leandro-lucarella-sociomantic** [comment]
It looks like it should depend too on: `libstdc++6`, `libc6` and `libgcc1`.

(according to the [Debian Policy](https://www.debian.org/doc/debian-policy/ch-binary.html), the package should depend on any non-Essential package)

**Comment by andreas-bok-sociomantic** [comment]
So in effect, cmd args for building the normal libdrizzle-redux package in `deb/build` should be

```
...
--depends zlib1g \
--depends libstdc++6 \
--depends libc6 \
--depends libgcc1 \
...
```

https://github.com/andreas-bok-sociomantic/libdrizzle-redux/blob/remove-dependencies-from-deb/deb/build#L46

**Comment by leandro-lucarella-sociomantic** [comment]
Yup.

**Comment by andreas-bok-sociomantic** [comment]
Great, updated based on comments from @leandro-lucarella-sociomantic, if it LGTY I will merge

**Comment by ben-palmer-sociomantic** [comment]
LGTM, any thing else from your side @leandro-lucarella-sociomantic ?

**Comment by leandro-lucarella-sociomantic** [comment]
LGTM

**Comment by ben-palmer-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was a10a7566b14fbfa10306501275c4e82a68d9ac3a, new (rebased) HEAD is 5183c892275270fb33b6f818da0d3ad4ab998d53

**Pull request closed without merging**
