### PR TITLE
Remove blank pages from generated pdf doc

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
Add latex_elements option to Sphinx config file
Ensures blank pages are removed after title and TOC

Addresses #45

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
@ben-palmer-sociomantic, this could go into v5.4.2 as well.

**Comment by ben-palmer-sociomantic** [comment]
LGTM, I don't really know what it is doing though.

**Comment by andreas-bok-sociomantic** [comment]
> LGTM, I don't really know what it is doing though.

Fixes some latex setting which meant that there was a blank page after the cover page

**Comment by ben-palmer-sociomantic** [comment]
Ok, I think I understand, LGTM.

**Pull request merged**
