### PR TITLE
Include revisions from launchpad dev branch 

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
This PR addresses a bug reported at the launchpad repo. 

> https://bugs.launchpad.net/libdrizzle/+bug/1211567
> Bug Description
> 
> The drizzle_connect() call blocks even if libdrizzle has been put in non-blocking mode. It does a nonblocking connect() call, but then libdrizzle blocks internally on poll in connect_poll() before returning to the caller, even if drizzle_options_set_non_blocking() has been used.

The bug was fixed in the dev branch https://code.launchpad.net/~wiml-omni/libdrizzle/nonblocking, thus this PR merely rebases that branch on the current master.

### CODE REVIEW

**Comment by andreas-bok-sociomantic** [comment]
The PR is ready for review, but can not be merged before it has been tested with actual apps/programs using the library

**Comment by ben-palmer-sociomantic** [comment]
Can this be unblocked now?

**Comment by andreas-bok-sociomantic** [comment]
> Can this be unblocked now?

Not yet. Still needs confirmation for apps using libdrizzle to write to the db.

**Comment by andreas-bok-sociomantic** [comment]
This patch has been tested and is ready for review.

**Comment by ben-palmer-sociomantic** [comment]
I have had a look and it seems that there are a few issues with indentations but I think these might be better to address in a later PR. Otherwise LGTM.

**Comment by andreas-bok-sociomantic** [comment]
> I have had a look and it seems that there are a few issues with indentations but I think these might be better to address in a later PR. 

Yes, would rather keep this as close to the original changes as possible

**Comment by andreas-bok-sociomantic** [comment]
@ben-palmer-sociomantic , if you are happy with this, feel free to merge

**Comment by ben-palmer-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 5876d3297bb2536ba9400965ec90fead4806835b, new (rebased) HEAD is 6b0f8ba8335015c4dd7213abd611f6fddfd57365

**Comment by andreas-bok-sociomantic** [comment]
TX!!

**Pull request closed without merging**
