### PR TITLE
Update submodule beaver from v0.1.4 to v0.2.1

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
* beaver v0.1.4(3c827c9)...v0.2.0(19f5888) (10 commits)
  > Add a simple Makefile for easy local testing
  > dlang: Make install install DMD automatically
  > install: Use gen-dockerfile if beaver.Dockerfile is present
  > docker: Add new gen-dockerfile command
  > Add a local-test file to ease running test locally
  (...)

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
Is this actually a bug fix? Its not obvious to me that this belongs in `v5.5.7`.

**Comment by andreas-bok-sociomantic** [comment]
> Is this actually a bug fix? Its not obvious to me that this belongs in v5.5.7.

True, given that it updates to the next minor version of `beaver`. I do however think that when doing a patch update of the submodule patch, it should be included in a library patch release.

**Comment by andreas-bok-sociomantic** [comment]
Updated.
Changed base branch to `v5.x.x` and milestone to [v5.7](https://github.com/sociomantic-tsunami/libdrizzle-redux/milestone/23)

**Comment by ben-palmer-sociomantic** [comment]
> True, given that it updates to the next minor version of beaver. I do however think that when doing a patch update of the submodule patch, it should be included in a library patch release.

Yep agreed, its also in line with the Neptune documentation: https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-maintainer.rst#a-note-on-updating-submodules

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Pull request merged**
