### PR TITLE
Advance submodule beaver

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**

### CODE REVIEW

**Comment by hatem-oraby-sociomantic** [comment]
LGTM, I'd just suggest that you rename the commit message from just:
`Advance submodule beaver`
To:
`Advance submodule beaver from v0.1.0 to v0.1.1`

That would make the git log summary a little bit more helpful

**Comment by andreas-bok-sociomantic** [comment]
Updated ci message title

**Comment by hatem-oraby-sociomantic** [comment]
LGTM, waiting for travis.

**Comment by andreas-bok-sociomantic** [comment]
Tx :)

**Pull request merged**
