### PR TITLE
Update beaver submodule to v0.3.0

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
* beaver v0.2.2(480e6f5)...v0.3.0(3f00ea2) (14 commits)
  > Convert release notes to the new format
  > dlang make: Upload codecov reports automatically
  > dlang: Add command to send reports to codecov
  > dlang: Pass a few extra Makd env variables to make
  > dlang: Add a command to release converted D2 tags
  (...)

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Why v5.7.x ?

**Comment by andreas-bok-sociomantic** [comment]
> Why v5.7.x ?

Not a breaking change. You wan't it in a new minor release?

**Comment by mathias-lang-sociomantic** [comment]
Not a big deal I think, I was just surprised to see it here.

**Comment by andreas-bok-sociomantic** [comment]
libdrizzle-redux is full of surprises. One big easter-egg

**Comment by andreas-bok-sociomantic** [comment]
Tx

**Pull request merged**
